spring:
  application:
    name: api-gateway

server:
  port: '8083'

logging:
  level:
    org:
      springframework:
        cloud:
          gateway: INFO
          loadbalancer: WARN
        web: WARN
