server:
  port: '8081'

spring:
  application:
    name: song-service
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: 'false'
  datasource:
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5439/song-db}
