server:
  port: '8082'

spring:
  application:
    name: resource-processor
  rabbitmq:
    password: ${SPRING_RABBITMQ_PASSWORD:guest}
    port: ${SPRING_RABBITMQ_PORT:5672}
    host: ${SPRING_RABBITMQ_HOST:localhost}
    username: ${SPRING_RABBITMQ_USERNAME:guest}
  cloud:
    stream:
      bindings:
        resourceUploaded-in-0:
          destination: resource.uploaded
          group: resource-processor
          consumer:
            max-attempts: '3'
            retryable-exceptions:
              java.lang.IllegalArgumentException: 'false'
        resourceProcessed-out-0:
          destination: resource.processed
          producer:
            required-groups: resource-service
      rabbit:
        bindings:
          resourceUploaded-in-0:
            consumer:
              exchangeType: topic
              republish-to-dlq: 'true'
              auto-bind-dlq: 'true'
          resourceProcessed-out-0:
            producer:
              exchangeType: topic
              auto-bind-dlq: 'true'

management:
  endpoints:
    web:
      exposure:
        include: health,refresh,prometheus,metrics
